---
title: AALS
timezone: America/Sao_Paulo
collections:
  destaques:
    title: Destaques
    output: false
  posts:
    title: Posts
    output: true
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:year/:month/:day/:title/"
    cover_image: 
    videos: []
- scope:
    path: ''
    type: pages
  values:
    layout: page
    icon_image: 
    title_color: 
    cover_image: 
- scope:
    path: ''
    type: slides
  values:
    image: 
    image-position: 
    text-position: 
    classes: 
- scope:
    path: ''
    type: destaques
  values:
    image: 
description: Há 30 anos rompendo fronteiras e encurtando distâncias.
baseurl: 
url: https://copatecnologia.com.br
permalink: "/:pretty/"
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
paginate: 8
paginate_path: "/blog/:num/"
sass:
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- node_modules
- npm-debug.log
- webpack.config.js
- ".babelrc"
- README.md
- _scripts/
long-title: AAL da Silva Serviços de Apoio Administrativos
endereco:
- Rua do Alecrim, 310 - Malota
- Jundiaí - SP | 13211-546 | Brasil
telefones:
- numero: "+5511999890215"
  rotulo: "+55 (11) 99989-0215"
  whatsapp: true
email: alberto.silva@aals.com.br
social:
- label: Facebook
  link: http://facebook.com/---
  icone: facebook
- label: Instagram
  link: http://instagram.com/---
  icone: instagram
- label: Pinterest
  link: http://pinterest.com/---
  icone: pinterest
- label: Twitter
  link: http://twitter.com/---
  icone: twitter
- label: Linkedin
  link: http://linkedin.com/---
  icone: linkedin
- label: Youtube
  link: http://youtube.com/---
  icone: youtube
disqus-name: aals-logistica
google-analytics-id: 
blog:
  icon_image: "/uploads/rss.svg"
  title_color: "#7ac143"
