---
title: AALS Logística
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
lang: pt_BR
description: Não se esqueça de preencher a descrição do site.
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
sass:
  style: compressed
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- CNAME
- README.md
